#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-libsass
Version  : 0.20.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/1a/12/90961539dec2eb3e0708e33585f89495c65814636bf32d44c7a829e4ef48/libsass-0.20.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/1a/12/90961539dec2eb3e0708e33585f89495c65814636bf32d44c7a829e4ef48/libsass-0.20.0.tar.gz
Summary  : Sass for Python: A straightforward binding of libsass for Python.
Group    : Development/Tools
License  : MIT
Requires: python-libsass-bin = %{version}-%{release}
Requires: python-libsass-license = %{version}-%{release}
Requires: python-libsass-python = %{version}-%{release}
Requires: python-libsass-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : libsass-dev
BuildRequires : six

%description
=====================================

%package bin
Summary: bin components for the python-libsass package.
Group: Binaries
Requires: python-libsass-license = %{version}-%{release}

%description bin
bin components for the python-libsass package.


%package license
Summary: license components for the python-libsass package.
Group: Default

%description license
license components for the python-libsass package.


%package python
Summary: python components for the python-libsass package.
Group: Default
Requires: python-libsass-python3 = %{version}-%{release}

%description python
python components for the python-libsass package.


%package python3
Summary: python3 components for the python-libsass package.
Group: Default
Requires: python3-core
Provides: pypi(libsass)
Requires: pypi(six)

%description python3
python3 components for the python-libsass package.


%prep
%setup -q -n libsass-0.20.0
cd %{_builddir}/libsass-0.20.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596136384
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-libsass
cp %{_builddir}/libsass-0.20.0/LICENSE %{buildroot}/usr/share/package-licenses/python-libsass/f808e63518e21c38c4e7b380baeec7e0c8859070
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/bin/sassc

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pysassc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-libsass/f808e63518e21c38c4e7b380baeec7e0c8859070

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
